name: easy_localization_generator
description: Generates the localization keys from an online Google Sheet or a local csv file.
version: 0.3.1
# author: Rin Luu Van <rinlv.hn@gmail.com>
homepage: https://github.com/rinlv/easy_localization_generator
issue_tracker: https://github.com/rinlv/easy_localization_generator/issues

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.3.1
  build_config: ^1.1.1
  source_gen: ^1.2.7
  http: ^1.1.0
  path: ^1.8.3
  csv: ^5.0.2
  intl: ^0.18.0
  analyzer: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
